name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version in package.json
        run: npm version --no-git-tag-version "${{ inputs.version }}"

      - name: Build Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            # Install dependencies for Linux build
            sudo apt-get update
            sudo apt-get install -y librsvg2-bin icnsutils
            npm run release:github
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            npm run release:github
          else
            npm run release:github
          fi
        shell: bash

      - name: Upload release assets
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'  # Only upload from one platform to avoid duplicates
        with:
          name: release-assets-${{ matrix.os }}
          path: dist/**